# Generated by Django 5.2.8 on 2025-11-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_reviewer', 'Program Super User'), ('auditor', 'Auditor'), ('viewer', 'Viewer')], default='viewer', max_length=32),
        ),
    ]
